language: python
python:
  - "3.10"

dist: focal
sudo: required

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python -m pip install --upgrade pip && python manage.py test && flake8"