language: python
python:
  - "3.10"

dist: focal
sudo: required

services:
  - docker

before_script: pip3 install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"